version: '2'
services:
  mysql:
    container_name: ml-db
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'marcellavigne'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/marcellavigne
volumes:
  my-datavolume:
